#!/usr/bin/env bash
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js




npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN polis-react@0.0.1 No license field.



npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js


npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN polis-react@0.0.1 No license field.

RROR in ./src/components/landers/Features/FeatureSection.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/easy-to-start.svg in /server/src/components/landers/Features
 @ ./src/components/landers/Features/FeatureSection.js 25:27-64

ERROR in ./src/components/landers/Features/FeatureSection.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/participation-engagement.svg in /server/src/components/landers/Features
 @ ./src/components/landers/Features/FeatureSection.js 29:39-87

ERROR in ./src/components/landers/Features/FeatureSection.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/ai-insights.svg in /server/src/components/landers/Features
 @ ./src/components/landers/Features/FeatureSection.js 33:26-61

ERROR in ./src/components/landers/Features/FeatureSection.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/ai-powered-insights.svg in /server/src/components/landers/Features
 @ ./src/components/landers/Features/FeatureSection.js 37:33-76

ERROR in ./src/components/landers/Hero/Hero.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/polis-report-insights.png in /server/src/components/landers/Hero
 @ ./src/components/landers/Hero/Hero.js 25:35-80

ERROR in ./src/components/landers/Trust/Trust.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/canada.png in /server/src/components/landers/Trust
 @ ./src/components/landers/Trust/Trust.js 25:22-52

ERROR in ./src/components/landers/Trust/Trust.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/columbia.png in /server/src/components/landers/Trust
 @ ./src/components/landers/Trust/Trust.js 29:24-56

ERROR in ./src/components/landers/Trust/Trust.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../icons/marchon.png in /server/src/components/landers/Trust
 @ ./src/components/landers/Trust/Trust.js 33:23-54

 **************************************************************
 [872] ./~/highlight.js/lib/languages/irpf90.js 5.4 kB {0} [built]
  [873] ./~/highlight.js/lib/languages/java.js 3.01 kB {0} [built]
  [874] ./~/highlight.js/lib/languages/javascript.js 3.5 kB {0} [built]
  [875] ./~/highlight.js/lib/languages/json.js 1.02 kB {0} [built]
  [876] ./~/highlight.js/lib/languages/julia.js 6.36 kB {0} [built]
  [877] ./~/highlight.js/lib/languages/kotlin.js 2.84 kB {0} [built]
  [878] ./~/highlight.js/lib/languages/lasso.js 5.38 kB {0} [built]
  [879] ./~/highlight.js/lib/languages/less.js 5.03 kB {0} [built]
  [880] ./~/highlight.js/lib/languages/lisp.js 2.4 kB {0} [built]
  [881] ./~/highlight.js/lib/languages/livecodeserver.js 9.8 kB {0} [built]
  [882] ./~/highlight.js/lib/languages/livescript.js 4.3 kB {0} [built]
  [883] ./~/highlight.js/lib/languages/lua.js 1.7 kB {0} [built]
  [884] ./~/highlight.js/lib/languages/makefile.js 943 bytes {0} [built]
  [885] ./~/highlight.js/lib/languages/mathematica.js 65.6 kB {0} [built]
  [886] ./~/highlight.js/lib/languages/matlab.js 3.13 kB {0} [built]
  [887] ./~/highlight.js/lib/languages/mel.js 19.1 kB {0} [built]
  [888] ./~/highlight.js/lib/languages/mercury.js 2.99 kB {0} [built]
  [889] ./~/highlight.js/lib/languages/mizar.js 825 bytes {0} [built]
  [890] ./~/highlight.js/lib/languages/perl.js 4.93 kB {0} [built]
  [891] ./~/highlight.js/lib/languages/mojolicious.js 479 bytes {0} [built]
  [892] ./~/highlight.js/lib/languages/monkey.js 1.98 kB {0} [built]
  [893] ./~/highlight.js/lib/languages/nginx.js 2.02 kB {0} [built]
  [894] ./~/highlight.js/lib/languages/nimrod.js 2 kB {0} [built]
  [895] ./~/highlight.js/lib/languages/nix.js 1.07 kB {0} [built]
  [896] ./~/highlight.js/lib/languages/nsis.js 5.57 kB {0} [built]
  [897] ./~/highlight.js/lib/languages/objectivec.js 2.4 kB {0} [built]
  [898] ./~/highlight.js/lib/languages/ocaml.js 2.19 kB {0} [built]
  [899] ./~/highlight.js/lib/languages/openscad.js 1.64 kB {0} [built]
  [900] ./~/highlight.js/lib/languages/oxygene.js 2.6 kB {0} [built]
  [901] ./~/highlight.js/lib/languages/parser3.js 932 bytes {0} [built]
  [902] ./~/highlight.js/lib/languages/pf.js 1.81 kB {0} [built]
  [903] ./~/highlight.js/lib/languages/php.js 3.47 kB {0} [built]
  [904] ./~/highlight.js/lib/languages/powershell.js 2.86 kB {0} [built]
  [905] ./~/highlight.js/lib/languages/processing.js 3.59 kB {0} [built]
  [906] ./~/highlight.js/lib/languages/profile.js 1.02 kB {0} [built]
  [907] ./~/highlight.js/lib/languages/prolog.js 1.3 kB {0} [built]
  [908] ./~/highlight.js/lib/languages/protobuf.js 1 kB {0} [built]
  [909] ./~/highlight.js/lib/languages/puppet.js 5.19 kB {0} [built]
  [910] ./~/highlight.js/lib/languages/python.js 2.05 kB {0} [built]
  [911] ./~/highlight.js/lib/languages/q.js 1.24 kB {0} [built]
  [912] ./~/highlight.js/lib/languages/r.js 1.69 kB {0} [built]
  [913] ./~/highlight.js/lib/languages/rib.js 1.48 kB {0} [built]
  [914] ./~/highlight.js/lib/languages/roboconf.js 1.45 kB {0} [built]
  [915] ./~/highlight.js/lib/languages/rsl.js 1.35 kB {0} [built]
  [916] ./~/highlight.js/lib/languages/ruleslanguage.js 4.52 kB {0} [built]
  [917] ./~/highlight.js/lib/languages/rust.js 2.86 kB {0} [built]
  [918] ./~/highlight.js/lib/languages/scala.js 1.44 kB {0} [built]
  [919] ./~/highlight.js/lib/languages/scheme.js 4.37 kB {0} [built]
  [920] ./~/highlight.js/lib/languages/scilab.js 1.81 kB {0} [built]
  [921] ./~/highlight.js/lib/languages/scss.js 7.6 kB {0} [built]
  [922] ./~/highlight.js/lib/languages/smali.js 2.26 kB {0} [built]
  [923] ./~/highlight.js/lib/languages/smalltalk.js 1.33 kB {0} [built]
  [924] ./~/highlight.js/lib/languages/sml.js 1.99 kB {0} [built]
  [925] ./~/highlight.js/lib/languages/sqf.js 32.8 kB {0} [built]
  [926] ./~/highlight.js/lib/languages/sql.js 14.5 kB {0} [built]
  [927] ./~/highlight.js/lib/languages/stata.js 16.8 kB {0} [built]
  [928] ./~/highlight.js/lib/languages/step21.js 1.21 kB {0} [built]
  [929] ./~/highlight.js/lib/languages/stylus.js 8.33 kB {0} [built]
  [930] ./~/highlight.js/lib/languages/swift.js 4.56 kB {0} [built]
  [931] ./~/highlight.js/lib/languages/tcl.js 2.34 kB {0} [built]
  [932] ./~/highlight.js/lib/languages/tex.js 1.19 kB {0} [built]
  [933] ./~/highlight.js/lib/languages/thrift.js 942 bytes {0} [built]
  [934] ./~/highlight.js/lib/languages/tp.js 2.35 kB {0} [built]
  [935] ./~/highlight.js/lib/languages/twig.js 1.45 kB {0} [built]
  [936] ./~/highlight.js/lib/languages/typescript.js 3.21 kB {0} [built]
  [937] ./~/highlight.js/lib/languages/vala.js 1.49 kB {0} [built]
  [938] ./~/highlight.js/lib/languages/vbnet.js 2.46 kB {0} [built]
  [939] ./~/highlight.js/lib/languages/vbscript.js 1.73 kB {0} [built]
  [940] ./~/highlight.js/lib/languages/vbscript-html.js 178 bytes {0} [built]
  [941] ./~/highlight.js/lib/languages/verilog.js 1.71 kB {0} [built]
  [942] ./~/highlight.js/lib/languages/vhdl.js 2.32 kB {0} [built]
  [943] ./~/highlight.js/lib/languages/vim.js 9.34 kB {0} [built]
  [944] ./~/highlight.js/lib/languages/x86asm.js 20.9 kB {0} [built]
  [945] ./~/highlight.js/lib/languages/xl.js 2.57 kB {0} [built]
  [946] ./~/highlight.js/lib/languages/xquery.js 1.98 kB {0} [built]
  [947] ./~/highlight.js/lib/languages/zephir.js 3.05 kB {0} [built]
  [948] ./src/components/overall-stats.js 5 kB {0} [built]
  [949] ./src/components/account.js 10.6 kB {0} [built]
  [950] ./src/components/stripe-form.js 8.43 kB {0} [built]
  [951] ./~/react-stripe-elements/lib/index.js 1.47 kB {0} [built]
  [952] ./~/react-stripe-elements/lib/components/Provider.js 3.88 kB {0} [built]
  [953] ./~/react-stripe-elements/lib/components/inject.js 6.6 kB {0} [built]
  [954] ./~/react-stripe-elements/lib/components/Elements.js 4.32 kB {0} [built]
  [955] ./~/react-stripe-elements/lib/components/Element.js 5.79 kB {0} [built]
  [956] ./~/react-stripe-elements/lib/utils/shallowEqual.js 357 bytes {0} [built]
  [957] ./src/components/container.js 4.43 kB {0} [built]
  [958] ./src/components/conversation-admin/container.js 7.33 kB {0} [built]
  [959] ./~/react-markdown/src/react-markdown.js 1.28 kB {0} [built]
  [960] ./~/commonmark/lib/index.js 515 bytes {0} [built]
  [961] ./~/commonmark/lib/node.js 6.04 kB {0} [built]
  [962] ./~/commonmark/lib/blocks.js 28.2 kB {0} [built]
  [963] ./~/commonmark/lib/common.js 2.96 kB {0} [built]
  [964] ./~/mdurl/encode.js 2.27 kB {0} [built]
  [965] ./~/mdurl/decode.js 2.87 kB {0} [built]
  [966] ./~/entities/index.js 808 bytes {0} [built]
  [967] ./~/entities/lib/encode.js 1.81 kB {0} [built]
  [968] ./~/entities/maps/xml.json 69 bytes {0} [built]
  [969] ./~/entities/maps/entities.json 29.1 kB {0} [built]
  [970] ./~/entities/lib/decode.js 1.63 kB {0} [built]
  [971] ./~/entities/maps/legacy.json 1.27 kB {0} [built]
  [972] ./~/entities/lib/decode_codepoint.js 622 bytes {0} [built]
  [973] ./~/entities/maps/decode.json 315 bytes {0} [built]
  [974] ./~/commonmark/lib/inlines.js 29.7 kB {0} [built]
  [975] ./~/commonmark/lib/normalize-reference.js 28.1 kB {0} [built]
  [976] ./~/commonmark/lib/from-code-point.js 1.98 kB {0} [built]
  [977] ./~/string.prototype.repeat/repeat.js 1.18 kB {0} [built]
  [978] ./~/commonmark/lib/html.js 7.1 kB {0} [built]
  [979] ./~/commonmark/lib/xml.js 4.85 kB {0} [built]
  [980] ./~/commonmark-react-renderer/src/commonmark-react-renderer.js 7.63 kB {0} [built]
  [981] ./src/components/conversation-admin/conversation-config.js 25.8 kB {0} [built]
  [982] ./~/material-ui/lib/checkbox.js 6.32 kB {0} [built]
  [983] ./~/material-ui/lib/enhanced-switch.js 13.6 kB {0} [built]
  [984] ./~/material-ui/lib/utils/key-code.js 129 bytes {0} [built]
  [985] ./~/material-ui/lib/mixins/window-listenable.js 583 bytes {0} [built]
  [986] ./~/material-ui/lib/utils/events.js 976 bytes {0} [built]
  [987] ./~/material-ui/lib/clearfix.js 2.28 kB {0} [built]
  [988] ./~/material-ui/lib/before-after-wrapper.js 4.74 kB {0} [built]
  [989] ./~/material-ui/lib/ripples/focus-ripple.js 3.41 kB {0} [built]
  [990] ./~/react-addons-pure-render-mixin/index.js 72 bytes {0} [built]
  [991] ./~/react/lib/ReactComponentWithPureRenderMixin.js 1.51 kB {0} [built]
  [992] ./~/react/lib/shallowCompare.js 694 bytes {0} [built]
  [993] ./~/material-ui/lib/transition-groups/scale-in.js 3.18 kB {0} [built]
  [994] ./~/react-addons-transition-group/index.js 59 bytes {0} [built]
  [995] ./~/react/lib/ReactTransitionGroup.js 6.14 kB {0} [built]
  [996] ./~/react/lib/ReactTransitionChildMapping.js 3.14 kB {0} [built]
  [997] ./~/material-ui/lib/transition-groups/scale-in-child.js 4.02 kB {0} [built]
  [998] ./~/material-ui/lib/ripples/touch-ripple.js 4.8 kB {0} [built]
  [999] ./~/material-ui/lib/utils/dom.js 1.91 kB {0} [built]
 [1000] ./~/material-ui/lib/ripples/circle-ripple.js 3.04 kB {0} [built]
 [1001] ./~/material-ui/lib/paper.js 3.58 kB {0} [built]
 [1002] ./~/material-ui/lib/utils/prop-types.js 722 bytes {0} [built]
 [1003] ./~/material-ui/lib/svg-icons/toggle/check-box-outline-blank.js 572 bytes {0} [built]
 [1004] ./~/material-ui/lib/svg-icon.js 3.67 kB {0} [built]
 [1005] ./~/material-ui/lib/svg-icons/toggle/check-box.js 577 bytes {0} [built]
 [1006] ./src/util/component-helpers.js 960 bytes {0} [built]
 [1007] ./src/components/conversation-admin/no-permission.js 5.5 kB {0} [built]
 [1008] ./src/settings.js 1.66 kB {0} [built]
 [1009] ./src/components/conversation-admin/moderate-comments-seed.js 7.96 kB {0} [built]
 [1010] ./src/components/conversation-admin/moderate-comments-seed-tweet.js 8.64 kB {0} [built]
 [1011] ./src/components/conversation-admin/conversation-stats.js 15.9 kB {0} [built]
 [1012] ./src/util/data-export-date-setup.js 2.62 kB {0} [built]
 [1013] ./src/components/conversation-admin/conversation-stats-number-cards.js 6.77 kB {0} [built]
 [1014] ./src/components/conversation-admin/conversation-stats-number-card.js 6.35 kB {0} [built]
 [1015] ./src/components/conversation-admin/conversation-stats-votes-timescale.js 6.1 kB {0} [built]
 [1016] ./~/victory-chart/lib/index.js 90 bytes {0} [built]
 [1017] ./~/victory-chart/lib/components/victory-chart.js 36.7 kB {0} [built]
 [1018] ./~/victory-util/lib/index.js 1.47 kB {0} [built]
 [1019] ./~/victory-util/lib/chart.js 2.54 kB {0} [built]
 [1020] ./~/lodash/object/transform.js 2.15 kB {0} [built]
 [1021] ./~/lodash/internal/arrayEach.js 534 bytes {0} [built]
 [1022] ./~/lodash/internal/baseCallback.js 1.06 kB {0} [built]
 [1023] ./~/lodash/internal/baseMatches.js 824 bytes {0} [built]
 [1024] ./~/lodash/internal/baseIsMatch.js 1.46 kB {0} [built]
 [1025] ./~/lodash/internal/baseIsEqual.js 1.09 kB {0} [built]
 [1026] ./~/lodash/internal/baseIsEqualDeep.js 3.34 kB {0} [built]
 [1027] ./~/lodash/internal/equalArrays.js 1.8 kB {0} [built]
 [1028] ./~/lodash/internal/arraySome.js 591 bytes {0} [built]
 [1029] ./~/lodash/internal/equalByTag.js 1.58 kB {0} [built]
 [1030] ./~/lodash/internal/equalObjects.js 2.37 kB {0} [built]
 [1031] ./~/lodash/object/keys.js 1.3 kB {0} [built]
 [1032] ./~/lodash/internal/getNative.js 456 bytes {0} [built]
 [1033] ./~/lodash/lang/isNative.js 1.29 kB {0} [built]
 [1034] ./~/lodash/lang/isFunction.js 1.06 kB {0} [built]
 [1035] ./~/lodash/lang/isObject.js 732 bytes {0} [built]
 [1036] ./~/lodash/internal/isObjectLike.js 289 bytes {0} [built]
 [1037] ./~/lodash/internal/isArrayLike.js 372 bytes {0} [built]
 [1038] ./~/lodash/internal/getLength.js 440 bytes {0} [built]
 [1039] ./~/lodash/internal/baseProperty.js 351 bytes {0} [built]
 [1040] ./~/lodash/internal/isLength.js 644 bytes {0} [built]
 [1041] ./~/lodash/internal/shimKeys.js 1.14 kB {0} [built]
 [1042] ./~/lodash/lang/isArguments.js 963 bytes {0} [built]
 [1043] ./~/lodash/lang/isArray.js 1.16 kB {0} [built]
 [1044] ./~/lodash/internal/isIndex.js 778 bytes {0} [built]
 [1045] ./~/lodash/object/keysIn.js 1.66 kB {0} [built]
 [1046] ./~/lodash/lang/isTypedArray.js 2.5 kB {0} [built]
 [1047] ./~/lodash/internal/toObject.js 308 bytes {0} [built]
 [1048] ./~/lodash/internal/getMatchData.js 523 bytes {0} [built]
 [1049] ./~/lodash/internal/isStrictComparable.js 420 bytes {0} [built]
 [1050] ./~/lodash/object/pairs.js 800 bytes {0} [built]
 [1051] ./~/lodash/internal/baseMatchesProperty.js 1.4 kB {0} [built]
 [1052] ./~/lodash/internal/baseGet.js 750 bytes {0} [built]
 [1053] ./~/lodash/internal/baseSlice.js 832 bytes {0} [built]
 [1054] ./~/lodash/internal/isKey.js 848 bytes {0} [built]
 [1055] ./~/lodash/array/last.js 377 bytes {0} [built]
 [1056] ./~/lodash/internal/toPath.js 806 bytes {0} [built]
 [1057] ./~/lodash/internal/baseToString.js 329 bytes {0} [built]
 [1058] ./~/lodash/internal/bindCallback.js 1.22 kB {0} [built]
 [1059] ./~/lodash/utility/identity.js 355 bytes {0} [built]
 [1060] ./~/lodash/utility/property.js 799 bytes {0} [built]
 [1061] ./~/lodash/internal/basePropertyDeep.js 476 bytes {0} [built]
 [1062] ./~/lodash/internal/baseCreate.js 569 bytes {0} [built]
 [1063] ./~/lodash/internal/baseForOwn.js 475 bytes {0} [built]
 [1064] ./~/lodash/internal/baseFor.js 608 bytes {0} [built]
 [1065] ./~/lodash/internal/createBaseFor.js 709 bytes {0} [built]
 [1066] ./~/lodash/object/merge.js 1.71 kB {0} [built]
 [1067] ./~/lodash/internal/baseMerge.js 1.92 kB {0} [built]
 [1068] ./~/lodash/internal/baseMergeDeep.js 2.39 kB {0} [built]
 [1069] ./~/lodash/internal/arrayCopy.js 454 bytes {0} [built]
 [1070] ./~/lodash/lang/isPlainObject.js 2.23 kB {0} [built]
 [1071] ./~/lodash/internal/baseForIn.js 478 bytes {0} [built]
 [1072] ./~/lodash/lang/toPlainObject.js 726 bytes {0} [built]
 [1073] ./~/lodash/internal/baseCopy.js 545 bytes {0} [built]
 [1074] ./~/lodash/internal/createAssigner.js 1.29 kB {0} [built]
 [1075] ./~/lodash/internal/isIterateeCall.js 906 bytes {0} [built]
 [1076] ./~/lodash/function/restParam.js 1.9 kB {0} [built]
 [1077] ./~/lodash/collection/some.js 2.36 kB {0} [built]
 [1078] ./~/lodash/internal/baseSome.js 647 bytes {0} [built]
 [1079] ./~/lodash/internal/baseEach.js 489 bytes {0} [built]
 [1080] ./~/lodash/internal/createBaseEach.js 913 bytes {0} [built]
 [1081] ./~/victory-util/lib/collection.js 1.85 kB {0} [built]
 [1082] ./~/lodash/collection/every.js 2.26 kB {0} [built]
 [1083] ./~/lodash/internal/arrayEvery.js 594 bytes {0} [built]
 [1084] ./~/lodash/internal/baseEvery.js 653 bytes {0} [built]
 [1085] ./~/lodash/lang/isDate.js 851 bytes {0} [built]
 [1086] ./~/victory-util/lib/data.js 10.4 kB {0} [built]
 [1087] ./~/lodash/array/compact.js 658 bytes {0} [built]
 [1088] ./~/lodash/array/findIndex.js 1.7 kB {0} [built]
 [1089] ./~/lodash/internal/createFindIndex.js 594 bytes {0} [built]
 [1090] ./~/lodash/internal/baseFindIndex.js 709 bytes {0} [built]
 [1091] ./~/lodash/array/flatten.js 936 bytes {0} [built]
 [1092] ./~/lodash/internal/baseFlatten.js 1.29 kB {0} [built]
 [1093] ./~/lodash/internal/arrayPush.js 437 bytes {0} [built]
 [1094] ./~/lodash/array/take.js 912 bytes {0} [built]
 [1095] ./~/lodash/array/union.js 716 bytes {0} [built]
 [1096] ./~/lodash/internal/baseUniq.js 1.53 kB {0} [built]
 [1097] ./~/lodash/internal/baseIndexOf.js 678 bytes {0} [built]
 [1098] ./~/lodash/internal/indexOfNaN.js 657 bytes {0} [built]
 [1099] ./~/lodash/internal/cacheIndexOf.js 586 bytes {0} [built]
 [1100] ./~/lodash/internal/createCache.js 650 bytes {0} [built]
 [1101] ./~/lodash/internal/SetCache.js 706 bytes {0} [built]
 [1102] ./~/lodash/internal/cachePush.js 379 bytes {0} [built]
 [1103] ./~/lodash/lang/isEmpty.js 1.23 kB {0} [built]
 [1104] ./~/lodash/lang/isString.js 889 bytes {0} [built]
 [1105] ./~/lodash/utility/range.js 1.7 kB {0} [built]
 [1106] ./~/lodash/array/uniq.js 2.57 kB {0} [built]
 [1107] ./~/lodash/internal/sortedUniq.js 742 bytes {0} [built]
 [1108] ./~/lodash/array/zipObject.js 1.13 kB {0} [built]
 [1109] ./~/lodash/array/zip.js 625 bytes {0} [built]
 [1110] ./~/lodash/array/unzip.js 1.33 kB {0} [built]
 [1111] ./~/lodash/internal/arrayFilter.js 630 bytes {0} [built]
 [1112] ./~/lodash/internal/arrayMap.js 553 bytes {0} [built]
 [1113] ./~/victory-util/lib/style.js 2.41 kB {0} [built]
 [1114] ./~/reduce-css-calc/index.js 4.23 kB {0} [built]
 [1115] ./~/balanced-match/index.js 1.16 kB {0} [built]
 [1116] ./~/reduce-function-call/index.js 1.91 kB {0} [built]
 [1117] ./~/reduce-function-call/~/balanced-match/index.js 554 bytes {0} [built]
 [1118] ./~/math-expression-evaluator/src/formula_evaluator.js 1.6 kB {0} [built]
 [1119] ./~/math-expression-evaluator/src/postfix_evaluator.js 3.03 kB {0} [built]
 [1120] ./~/math-expression-evaluator/src/postfix.js 1.32 kB {0} [built]
 [1121] ./~/math-expression-evaluator/src/lexer.js 9.24 kB {0} [built]
 [1122] ./~/math-expression-evaluator/src/math_function.js 2.51 kB {0} [built]
 [1123] ./~/lodash.indexof/index.js 8.17 kB {0} [built]
 [1124] ./~/victory-util/lib/scale.js 3.46 kB {0} [built]
 [1125] ./~/lodash/collection/includes.js 2.05 kB {0} [built]
 [1126] ./~/lodash/object/values.js 691 bytes {0} [built]
 [1127] ./~/lodash/internal/baseValues.js 593 bytes {0} [built]
 [1128] ./~/victory-util/~/d3-scale/build/d3-scale.js 25.2 kB {0} [built]
 [1129] ./~/d3-color/build/d3-color.js 13.8 kB {0} [built]
 [1130] ./~/d3-interpolate/build/d3-interpolate.js 12.3 kB {0} [built]
 [1131] ./~/d3-arrays/build/d3-arrays.js 13 kB {0} [built]
 [1132] ./~/d3-format/build/d3-format.js 14.6 kB {0} [built]
 [1133] ./~/d3-time-format/build/d3-time-format.js 27.8 kB {0} [built]
 [1134] ./~/d3-time/build/d3-time.js 10.6 kB {0} [built]
 [1135] ./~/victory-util/lib/domain.js 2.98 kB {0} [built]
 [1136] ./~/victory-util/lib/log.js 376 bytes {0} [built]
 [1137] ./~/victory-util/lib/type.js 1.45 kB {0} [built]
 [1138] ./~/victory-util/lib/prop-types.js 3.97 kB {0} [built]
 [1139] ./~/lodash/function/bind.js 1.68 kB {0} [built]
 [1140] ./~/lodash/internal/createWrapper.js 3.08 kB {0} [built]
 [1141] ./~/lodash/internal/baseSetData.js 465 bytes {0} [built]
 [1142] ./~/lodash/internal/metaMap.js 224 bytes {0} [built]
 [1143] ./~/lodash/internal/createBindWrapper.js 622 bytes {0} [built]
 [1144] ./~/lodash/internal/createCtorWrapper.js 1.5 kB {0} [built]
 [1145] ./~/lodash/internal/createHybridWrapper.js 4.15 kB {0} [built]
 [1146] ./~/lodash/internal/composeArgs.js 1.12 kB {0} [built]
 [1147] ./~/lodash/internal/composeArgsRight.js 1.18 kB {0} [built]
 [1148] ./~/lodash/internal/isLaziable.js 705 bytes {0} [built]
 [1149] ./~/lodash/internal/LazyWrapper.js 701 bytes {0} [built]
 [1150] ./~/lodash/internal/baseLodash.js 176 bytes {0} [built]
 [1151] ./~/lodash/internal/getData.js 333 bytes {0} [built]
 [1152] ./~/lodash/utility/noop.js 328 bytes {0} [built]
 [1153] ./~/lodash/internal/getFuncName.js 542 bytes {0} [built]
 [1154] ./~/lodash/internal/realNames.js 98 bytes {0} [built]
 [1155] ./~/lodash/chain/lodash.js 5.58 kB {0} [built]
 [1156] ./~/lodash/internal/LodashWrapper.js 658 bytes {0} [built]
 [1157] ./~/lodash/internal/wrapperClone.js 513 bytes {0} [built]
 [1158] ./~/lodash/internal/reorder.js 896 bytes {0} [built]
 [1159] ./~/lodash/internal/replaceHolders.js 738 bytes {0} [built]
 [1160] ./~/lodash/internal/setData.js 1.06 kB {0} [built]
 [1161] ./~/lodash/date/now.js 619 bytes {0} [built]
 [1162] ./~/lodash/internal/createPartialWrapper.js 1.52 kB {0} [built]
 [1163] ./~/lodash/internal/mergeData.js 3.02 kB {0} [built]
 [1164] ./~/victory-chart/~/victory-axis/lib/index.js 88 bytes {0} [built]
 [1165] ./~/victory-chart/~/victory-axis/lib/components/victory-axis.js 21.9 kB {0} [built]
 [1166] ./~/victory-chart/~/d3-scale/build/d3-scale.js 25.2 kB {0} [built]
 [1167] ./~/victory-label/lib/index.js 90 bytes {0} [built]
 [1168] ./~/victory-label/lib/components/victory-label.js 10.3 kB {0} [built]
 [1169] ./~/victory-animation/lib/index.js 98 bytes {0} [built]
 [1170] ./~/victory-animation/lib/components/victory-animation.js 9.31 kB {0} [built]
 [1171] ./~/d3-ease/build/d3-ease.js 5.36 kB {0} [built]
 [1172] ./~/d3-timer/build/d3-timer.js 2.83 kB {0} [built]
 [1173] ./~/victory-animation/lib/util.js 6 kB {0} [built]
 [1174] ./~/victory-chart/~/victory-axis/lib/components/axis-line.js 3.16 kB {0} [built]
 [1175] ./~/victory-chart/~/victory-axis/lib/components/grid.js 3.87 kB {0} [built]
 [1176] ./~/victory-chart/~/victory-axis/lib/components/tick.js 5.81 kB {0} [built]
 [1177] ./~/victory-chart/~/victory-axis/lib/util.js 390 bytes {0} [built]
 [1178] ./~/victory-chart/~/victory-line/lib/index.js 88 bytes {0} [built]
 [1179] ./~/victory-chart/~/victory-line/lib/components/victory-line.js 18.7 kB {0} [built]
 [1180] ./~/victory-chart/~/victory-line/lib/components/line-segment.js 4.42 kB {0} [built]
 [1181] ./~/d3-shape/build/d3-shape.js 47.1 kB {0} [built]
 [1182] ./~/d3-path/build/d3-path.js 4.72 kB {0} [built]
 [1183] ./~/victory-chart/~/victory-line/lib/components/line-label.js 5.07 kB {0} [built]
 [1184] ./~/victory-line/lib/index.js 88 bytes {0} [built]
 [1185] ./~/victory-line/lib/components/victory-line.js 18 kB {0} [built]
 [1186] ./~/d3/d3.js 337 kB {0} [built]
 [1187] ./~/victory-line/~/victory-animation/lib/index.js 98 bytes {0} [built]
 [1188] ./~/victory-line/~/victory-animation/lib/components/victory-animation.js 7.26 kB {0} [built]
 [1189] ./~/victory-line/~/victory-animation/lib/util.js 5.95 kB {0} [built]
 [1190] ./~/victory-bar/lib/index.js 86 bytes {0} [built]
 [1191] ./~/victory-bar/lib/components/victory-bar.js 27 kB {0} [built]
 [1192] ./~/victory-bar/~/d3-scale/build/d3-scale.js 25.2 kB {0} [built]
 [1193] ./~/victory-bar/lib/components/bar.js 5.49 kB {0} [built]
 [1194] ./~/victory-bar/lib/components/bar-label.js 6.27 kB {0} [built]
 [1195] ./~/victory-axis/lib/index.js 88 bytes {0} [built]
 [1196] ./~/victory-axis/lib/components/victory-axis.js 21.9 kB {0} [built]
 [1197] ./~/d3-scale/build/d3-scale.js 31.6 kB {0} [built]
 [1198] ./~/d3-array/build/d3-array.js 17 kB {0} [built]
 [1199] ./~/victory-axis/lib/components/axis-line.js 3.16 kB {0} [built]
 [1200] ./~/victory-axis/lib/components/grid.js 3.87 kB {0} [built]
 [1201] ./~/victory-axis/lib/components/tick.js 5.81 kB {0} [built]
 [1202] ./~/victory-axis/lib/util.js 390 bytes {0} [built]
 [1203] ./src/components/conversation-admin/conversation-stats-vote-distribution.js 6.81 kB {0} [built]
 [1204] ./src/components/conversation-admin/conversation-stats-comments-timescale.js 6.26 kB {0} [built]
 [1205] ./src/components/conversation-admin/conversation-stats-commenters-voters.js 6.59 kB {0} [built]
 [1206] ./src/components/conversation-admin/moderate-comments.js 9.43 kB {0} [built]
 [1207] ./src/components/framework/nav-tab.js 8.36 kB {0} [built]
 [1208] ./src/components/conversation-admin/moderate-comments-todo.js 7.44 kB {0} [built]
 [1209] ./src/components/conversation-admin/comment.js 13.2 kB {0} [built]
 [1210] ./src/components/conversation-admin/participant-header.js 12.2 kB {0} [built]
 [1211] ./src/components/framework/verified-twitter-icon.js 10.6 kB {0} [built]
 [1212] ./src/components/conversation-admin/moderate-comments-accepted.js 7.21 kB {0} [built]
 [1213] ./src/components/conversation-admin/moderate-comments-rejected.js 7.21 kB {0} [built]
 [1214] ./src/components/conversation-admin/moderate-people.js 8.81 kB {0} [built]
 [1215] ./src/components/conversation-admin/moderate-people-default.js 9.5 kB {0} [built]
 [1216] ./src/components/conversation-admin/participant.js 9.18 kB {0} [built]
 [1217] ./src/components/conversation-admin/moderate-people-featured.js 8.32 kB {0} [built]
 [1218] ./src/components/conversation-admin/moderate-people-hidden.js 8.2 kB {0} [built]
 [1219] ./src/components/conversation-admin/data-export.js 12.9 kB {0} [built]
 [1220] ./~/material-ui/lib/radio-button.js 5.5 kB {0} [built]
 [1221] ./~/material-ui/lib/svg-icons/toggle/radio-button-unchecked.js 606 bytes {0} [built]
 [1222] ./~/material-ui/lib/svg-icons/toggle/radio-button-checked.js 657 bytes {0} [built]
 [1223] ./~/material-ui/lib/radio-button-group.js 4.67 kB {0} [built]
 [1224] ./~/material-ui/lib/select-field.js 5.63 kB {0} [built]
 [1225] ./~/material-ui/lib/drop-down-menu.js 11.8 kB {0} [built]
 [1226] ./~/material-ui/lib/svg-icons/navigation/arrow-drop-down.js 487 bytes {0} [built]
 [1227] ./~/material-ui/lib/menu/menu.js 19.6 kB {0} [built]
 [1228] ./~/material-ui/lib/utils/css-event.js 1.33 kB {0} [built]
 [1229] ./~/material-ui/lib/utils/key-line.js 273 bytes {0} [built]
 [1230] ./~/material-ui/lib/mixins/click-awayable.js 1.39 kB {0} [built]
 [1231] ./~/material-ui/lib/menu/menu-item.js 8.25 kB {0} [built]
 [1232] ./~/material-ui/lib/font-icon.js 3.52 kB {0} [built]
 [1233] ./~/material-ui/lib/toggle.js 6.43 kB {0} [built]
 [1234] ./~/material-ui/lib/menu/link-menu-item.js 4.04 kB {0} [built]
 [1235] ./~/material-ui/lib/menu/subheader-menu-item.js 2.75 kB {0} [built]
 [1236] ./~/material-ui/lib/styles/typography.js 776 bytes {0} [built]
 [1237] ./src/components/conversation-admin/share-and-embed.js 9.19 kB {0} [built]
 [1238] ./src/components/conversation-admin/conversation-has-comments-check.js 8.82 kB {0} [built]
 [1239] ./src/components/conversation-admin/live.js 7.69 kB {0} [built]
 [1240] ./src/components/conversation-admin/summary.js 7.67 kB {0} [built]
 [1241] ./src/components/conversation-admin/summary-comment.js 11.2 kB {0} [built]
 [1242] ./src/components/framework/colors.js 767 bytes {0} [built]
 [1243] ./src/components/conversation-admin/summary-comment-barchart.js 6.82 kB {0} [built]
 [1244] ./src/components/conversation-admin/summary-stats.js 5.3 kB {0} [built]
 [1245] ./src/components/conversation-admin/summary-consensus.js 8.26 kB {0} [built]
 [1246] ./src/components/conversation-admin/summary-groups.js 6.64 kB {0} [built]
 [1247] ./src/components/conversation-admin/summary-group.js 7.27 kB {0} [built]
 [1248] ./src/components/conversation-admin/reports.js 5.53 kB {0} [built]
 [1249] ./src/components/conversation-admin/report-config.js 15.1 kB {0} [built]
 [1250] ./src/components/conversation-admin/report-comments.js 11 kB {0} [built]
 [1251] ./src/components/conversation-admin/report-comments-included.js 7.2 kB {0} [built]
 [1252] ./src/components/conversation-admin/report-comments-excluded.js 6.97 kB {0} [built]
 [1253] ./src/components/conversation-admin/reports-list.js 8.3 kB {0} [built]
 [1254] ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 455 bytes {0} [built]
 [1255] ./~/react-tap-event-plugin/src/defaultClickRejectionStrategy.js 151 bytes {0} [built]
 [1256] ./~/react-tap-event-plugin/src/TapEventPlugin.js 4.94 kB {0} [built]
 [1257] ./~/react-tap-event-plugin/src/TouchEventUtils.js 1.55 kB {0} [built]
 [1258] ./~/react-tap-event-plugin/~/fbjs/lib/keyOf.js 1.11 kB {0} [built]

ERROR in ./~/highlight.js/lib/languages/autoit.js
Module parse failed: /server/node_modules/highlight.js/lib/languages/autoit.js Maximum call stack size exceeded
You may need an appropriate loader to handle this file type.
RangeError: Maximum call stack size exceeded
    at Parser.applyPluginsBailResult (/server/node_modules/tapable/lib/Tapable.js:44:35)
    at Parser.evaluateExpression (/server/node_modules/webpack/lib/Parser.js:787:20)
    at Parser.<anonymous> (/server/node_modules/webpack/lib/Parser.js:66:16)
    at Parser.applyPluginsBailResult (/server/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/server/node_modules/webpack/lib/Parser.js:787:20)
    at Parser.<anonymous> (/server/node_modules/webpack/lib/Parser.js:66:16)
    at Parser.applyPluginsBailResult (/server/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/server/node_modules/webpack/lib/Parser.js:787:20)
    at Parser.<anonymous> (/server/node_modules/webpack/lib/Parser.js:66:16)
    at Parser.applyPluginsBailResult (/server/node_modules/tapable/lib/Tapable.js:48:50)
 @ ./~/highlight.js/lib/index.js 13:32-61



# cp -rf ./src/components/Landers/Icons ./src/components/landers/icons


cat<< EOF > .env_dev
export DEV_MODE=true
export STATIC_FILES_HOST=172.17.0.2
export STATIC_FILES_PORT=5001
export STATIC_FILES_ADMINDASH_PORT=5002
export DOMAIN_OVERRIDE=0.0.0.0:5000
export PORT=5000
export STRIPE_SECRET_KEY=sk_test_NFBDEThkpHCYBzXPJuBlY8TW
export DATABASE_URL=postgres://polis:polis@polisdb:5432/polis
export DATABASE_FOR_READS_NAME=DATABASE_URL
export DISABLE_INTERCOM=true
export ADMIN_UIDS="[]"
export ADMIN_EMAILS='["uzzal2k5@gmail.com"]'
export ADMIN_EMAIL_DATA_EXPORT="[]"
export ADMIN_EMAIL_DATA_EXPORT_TEST=[]
export ADMIN_EMAIL_EMAIL_TEST=[]
EOF